query_executor: Fixed race between Query.Release() and speculative executions
gocql/gocql pull request #1684
Opened 2023-03-30 12:41 UTC by wprzytula

As described in #1315, there is a race condition when there is more than one concurrent execution (by means of speculative execution) and `Query.Release()` is called after one of them completes. `Query.Release()` calls `Query.reset()`, which in turns zeroes the whole `Query`. Then, after another execution completes, it tries to access metrics, but they are already set to nil by the call to `Release()`, so a segfault is triggered.

The solution is quite simple: a ref counter is introduced into the `Query`. It is obviously initially set to 1. Every execution fiber (i.e. every execution goroutine) has the refcount atomically incremented before it is started, and decrements the refcount on completion. `Query.Release()` merely decrements the refcount. `Query.reset()` is called by whichever goroutine that decrements the refcount to 0.

Fixes: #1315

2023-04-03 08:23 UTC, mykaul commented
@martin-sucha - will you be able to review this change? TIA!

2023-04-04 08:23 UTC, martin-sucha requested changes
Thanks for the pull request! Code looks good to me. Could you please also update AUTHORS and CHANGELOG.md as per https://github.com/gocql/gocql/blob/master/CONTRIBUTING.md#minimum-requirement-checklist ?

2023-04-12 10:49 UTC, wprzytula commented
> Thanks for the pull request! Code looks good to me. Could you please also update AUTHORS and CHANGELOG.md as per https://github.com/gocql/gocql/blob/master/CONTRIBUTING.md#minimum-requirement-checklist ?

Done.

2023-04-19 12:06 UTC, wprzytula commented
@martin-sucha ping

2023-04-20 07:50 UTC, martin-sucha approved these changes

2023-04-20 07:57 UTC, merged

2023-04-20 07:57 UTC, martin-sucha commented
Thanks! Merged :rocket: