Support of now in seconds option for QUERY, BATCH and EXECUTE messages
gocql/gocql pull request #1781
Opened 2024-07-16 09:34 UTC by worryg0d

This PR provides support for [now_in_seconds](https://github.com/apache/cassandra/blob/42d18a83e4468827da234c68fad3e3058b368d7c/doc/native_protocol_v5.spec#L1455C1-L1456C1) optional field for QUERY, BATCH and EXECUTE messages as part of Native Protocol v5 support.
The implementation is mostly based on previous implementations for such optional fields as _timestamp_, _keyspace_, etc.

2024-08-28 09:31 UTC, lukasz-antoniak requested changes

2024-08-28 09:31 UTC, lukasz-antoniak commented on batch_test.go
> +	if ttl > 1800 {
I think this test is slightly better: [NowInSecondsIT.java](https://github.com/apache/cassandra-java-driver/blob/4.x/integration-tests/src/test/java/com/datastax/oss/driver/core/cql/NowInSecondsIT.java). Use `NowInSeconds` also in SELECT query, so that you can indeed read expected TTL difference.

2024-08-28 09:31 UTC, lukasz-antoniak commented on frame.go
> +		flags := uint32(flags)
I think changing flags to `int` type and truncating it for protocols before V5 would be cleaner.

2024-08-28 09:31 UTC, lukasz-antoniak commented on frame.go
> +		if opts.nowInSeconds {
After we refactor flag to be an integer, we can move this to a place where all flags are computed.

2024-10-01 13:31 UTC, joao-r-reis commented
Can this be closed in favor of #1822 ?

2024-10-01 14:56 UTC, worryg0d commented
> Can this be closed in favor of #1822 ?

Replied in #1778.

2024-10-08 15:16 UTC, closed without merging

2024-10-08 15:21 UTC, lukasz-antoniak commented on batch_test.go
> +	if ttl > 1800 {
This has been addressed in #1822.